name: our_wallet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  card_swiper: 2.0.4
  cupertino_icons: ^1.0.2
  curved_navigation_bar: 1.0.3
  dio: 5.2.1+1
  flutter_svg: 2.0.5
  firebase_auth: 4.6.3
  firebase_core: 2.14.0
  get: 4.6.5
  get_storage: 2.1.1
  google_fonts: 4.0.4
  image_picker: 1.0.0
  intl: 0.18.1
  lottie: 2.3.2
  pin_code_fields: 8.0.1
  shimmer: 3.0.0
  currency_text_input_formatter: 2.1.10
  animations: 2.0.7
  badges: 3.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_launcher_icons: 0.13.1
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/jpg/ow_logo_2.jpg
  ios: true
  min_sdk_android: 21

flutter: 
  assets: 
    - assets/png/
    - assets/jpg/
    - assets/svg/
    - assets/lottie/
  uses-material-design: true

