name: our_wallet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  shimmer: 3.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_launcher_icons: 0.13.1
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/png/ow_logo_2.png
  ios: true
  min_sdk_android: 21

flutter: 
  assets: 
    - assets/png/
  uses-material-design: true

