// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCww0u8kbUJ6WSXUQgOaLeD-DVJg1_GaDc',
    appId: '1:369804612352:web:78f5f9e5fed3359c7dd9e5',
    messagingSenderId: '369804612352',
    projectId: 'our-wallet-884ec',
    authDomain: 'our-wallet-884ec.firebaseapp.com',
    storageBucket: 'our-wallet-884ec.appspot.com',
    measurementId: 'G-K435MVH9H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD884VHEaGttKX15VMzAkfd9EbVSGCx8Yw',
    appId: '1:369804612352:android:5f7b35ebcb243f697dd9e5',
    messagingSenderId: '369804612352',
    projectId: 'our-wallet-884ec',
    storageBucket: 'our-wallet-884ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM-TDmtFmbvKzXs0-O1ZijgCJvtHLus30',
    appId: '1:369804612352:ios:eae264c62613e2907dd9e5',
    messagingSenderId: '369804612352',
    projectId: 'our-wallet-884ec',
    storageBucket: 'our-wallet-884ec.appspot.com',
    iosClientId: '369804612352-v92u8pbcrkffo28d7ag2e3ja8rvqsp24.apps.googleusercontent.com',
    iosBundleId: 'com.alfanmuazharin.ourWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM-TDmtFmbvKzXs0-O1ZijgCJvtHLus30',
    appId: '1:369804612352:ios:eae264c62613e2907dd9e5',
    messagingSenderId: '369804612352',
    projectId: 'our-wallet-884ec',
    storageBucket: 'our-wallet-884ec.appspot.com',
    iosClientId: '369804612352-v92u8pbcrkffo28d7ag2e3ja8rvqsp24.apps.googleusercontent.com',
    iosBundleId: 'com.alfanmuazharin.ourWallet',
  );
}
